name: Python Package using Conda

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: ['3.9', '3.10']

    steps:
    - uses: actions/checkout@v4

    # 安装 Miniconda
    - name: Setup Miniconda
      shell: powershell
      run: |
        $minicondaInstaller = "Miniconda3-latest-Windows-x86_64.exe"
        Invoke-WebRequest "https://repo.anaconda.com/miniconda/$minicondaInstaller" -OutFile "$minicondaInstaller"
        $installDir = "$env:USERPROFILE\miniconda3"
        Start-Process -FilePath ".\$minicondaInstaller" -ArgumentList "/S", "/D=$installDir" -Wait
        $env:PATH = "$installDir;$installDir\Scripts;$installDir\Library\bin;$env:PATH"
        [System.Environment]::SetEnvironmentVariable("PATH", $env:PATH, [System.EnvironmentVariableTarget]::User)
        & "$installDir\Scripts\conda" init powershell
        & "$installDir\Scripts\conda" init bash
        & conda --version

    # 配置镜像源
    - name: Setup Conda Mirror
      shell: powershell
      run: |
        conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
        conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/

    # 安装依赖
    - name: Install dependencies
      shell: powershell
      run: |
        conda env update --file environment.yml --name base

    # 创建 Conda 环境
    - name: Create conda environment
      shell: powershell
      run: |
        conda create -n testenv python=${{ matrix.python-version }} --yes
        conda activate testenv
        conda env update --file environment.yml --name testenv

    # 清理环境
    - name: Clean Conda Environment
      shell: powershell
      run: |
        conda clean --all --yes

    # 安装 flake8
    - name: Install flake8
      shell: powershell
      run: |
        conda install -n testenv flake8 requests=2.28.2 --yes

    # 运行 flake8
    - name: Lint with flake8
      shell: powershell
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # 构建包
    - name: Build package
      shell: powershell
      run: |
        python setup.py sdist bdist_wheel

    # 上传包
    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: dist/
